EmployeeTracking.UI/Models/ErrorViewModel.cs
using System;

namespace EmployeeTracking.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeTracking.UI/Controllers/EmployeeLeaveTypeController.cs
using EmployeeTracking.BusinessEngine.Contracts;
using EmployeeTracking.BusinessEngine.Implementaion;
using EmployeeTracking.Common.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeTracking.UI.Controllers
{
    public class EmployeeLeaveTypeController : Controller
    {
        private readonly IEmployeeLeaveTypeBusinessEngine _employeeLeaveTypeBusinessEngine;
        public EmployeeLeaveTypeController(IEmployeeLeaveTypeBusinessEngine employeeLeaveTypeBusinessEngine)
        {
            _employeeLeaveTypeBusinessEngine = employeeLeaveTypeBusinessEngine;
        }  
        public IActionResult Index()
        {
            var data = _employeeLeaveTypeBusinessEngine.GetAllEmployeeLeaveTypes();
            if (data.IsSuccess)
            {
                var result = data.Data;
                return View(result);
            }
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(EmployeeLeaveTypeVM employeeLeaveTypeVM)
        {
            if(ModelState.IsValid)
            {
                var data = _employeeLeaveTypeBusinessEngine.CreateEmployeeLeaveType(employeeLeaveTypeVM);
                if (data.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                return View(data);
            }
            else
            return View(employeeLeaveTypeVM);
        }
        public IActionResult Edit(int id)
        {
            var data = _employeeLeaveTypeBusinessEngine.GetAllEmployeeLeaveType(id);
            if(data.IsSuccess)
            {
                return View(data.Data);
            }
            return View();
        }
        [HttpPost]
        public IActionResult Edit(EmployeeLeaveTypeVM employeeLeaveTypeVM)
        {
            if (ModelState.IsValid)
            {
                var data = _employeeLeaveTypeBusinessEngine.UpdateEmployeeLeaveType(employeeLeaveTypeVM);
                if (data.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                return View(data);
            }
            else
                return View(employeeLeaveTypeVM);
        }
    }
}

EmployeeTracking.UI/Controllers/HomeController.cs
using EmployeeTracking.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeTracking.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeTracking.UI/Views/EmployeeLeaveType/Create.cshtml
@using EmployeeTracking.Common.ViewModel
@model EmployeeLeaveTypeVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Create" asp-controller="EmployeeLeaveType">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label for="exampleInputEmail1">İsim Giriniz</label>
        <input type="text" class="form-control" id="exampleInputName" placeholder="Enter Name" asp-for="Name">
    </div>
    <input type="submit" class="btn btn-success" value="Gönder" />
    <button type="button" class="btn btn-outline-info" onclick="deleteFormData()">Reset</button>
</form>
<script type="text/javascript">
    function deleteFormData() {
        document.forms[0].reset();
    }
</script>

EmployeeTracking.UI/Views/EmployeeLeaveType/Edit.cshtml
@using EmployeeTracking.Common.ViewModel
@model EmployeeLeaveTypeVM
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Edit" asp-controller="EmployeeLeaveType">
    <input type="hidden" asp-for="@Model.Id" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label for="exampleInputEmail1">İsim Giriniz</label>
        <input type="text" class="form-control" id="exampleInputName" asp-for="Name">
    </div>
    <input type="submit" class="btn btn-success" value="Gönder" />
    <button type="button" class="btn btn-outline-info" onclick="deleteFormData()">Reset</button>
</form>
<script type="text/javascript">
    function deleteFormData() {
        document.forms[0].reset();
    }
</script>

EmployeeTracking.UI/Views/EmployeeLeaveType/Index.cshtml
@using EmployeeTracking.Common.ViewModel
@model List<EmployeeLeaveTypeVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br />
<table class="table table-hover">
    <thead>
        <tr><th style="border:0" colspan="5" class="text-right">
            <a class="btn btn-success text-center" asp-controller="EmployeeLeaveType" asp-action="Create">Tip Ekle</a>
            </th>
        </tr>
        <tr>
            <th scope="col">İsim</th>
            <th scope="col">Oluşturulma Tarihi</th>
            <th scope="col" colspan="3">Seçenekler</th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.DateCreated</td>
                    <td>
                        <a class="btn btn-success" asp-controller="EmployeeLeaveType" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    </td>
                    <td>mdo</td>
                    <td>bos</td>
                </tr>
            }
        }  
    </tbody>
</table>

EmployeeTracking.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeTracking.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeTracking.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeTracking.UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeLeaveType" asp-action="Index">Çalışan İzin Tipi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>                
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EmployeeTracking.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>